name: Generate Plugin Data

on:
  schedule:
    - cron: '0 10 * * 0-6'
  workflow_dispatch:
  repository_dispatch:
    types: [new-release]

jobs:
  generate:
    name: Generate Plugin Data
    runs-on: windows-latest
    steps:
      - name: Get Branch Name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Repo And Check For Changes
        run: .\generate-repo.ps1

      - name: Commit Files
        continue-on-error: true
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -m "Regenerate Repo" --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" -a

      - name: Push Changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
